package galaxy

var questCriticalNames = []string{
	"Acamar",
	"Baratas",
	"Melina",
	"Regulas",
	"Zalkon",
	"Japori",
	"Kravat",
	"Devidia",
	"Gemulon",
	"Daled",
	"Nix",
	"Utopia",
}

var systemNamePool = []string{
	"Acamar", "Adahn", "Aldea", "Andevian", "Antedi",
	"Balosnee", "Baratas", "Brax", "Bretel", "Calondia",
	"Campor", "Capelle", "Carzon", "Castor", "Cestus",
	"Cheron", "Courteney", "Daled", "Damast", "Davlos",
	"Deneb", "Deneva", "Devidia", "Draylon", "Drema",
	"Endor", "Esmee", "Exo", "Ferris", "Festen",
	"Fourmi", "Frolix", "Gemulon", "Guinifer", "Hades",
	"Hamlet", "Helena", "Hulst", "Iodine", "Iralius",
	"Janus", "Japori", "Jarada", "Jason", "Kaylon",
	"Khefka", "Kira", "Klaatu", "Klaestron", "Korma",
	"Kravat", "Krios", "Laertes", "Largo", "Lave",
	"Ligon", "Lowry", "Magrat", "Malcoria", "Melina",
	"Mentar", "Merik", "Mintaka", "Montor", "Mordan",
	"Myrthe", "Nelvana", "Nix", "Nyle", "Odet",
	"Og", "Omega", "Omphalos", "Orias", "Othello",
	"Parade", "Penthara", "Picard", "Pollux", "Quator",
	"Rakhar", "Ran", "Regulas", "Relva", "Rhymus",
	"Rochani", "Rubicum", "Rutia", "Sarpeidon", "Sefalla",
	"Seltrice", "Sigma", "Sol", "Somari", "Stakoron",
	"Styris", "Talani", "Tamus", "Tantalos", "Tanuga",
	"Tarchannen", "Terosa", "Thera", "Titan", "Torin",
	"Triacus", "Turkana", "Tyrus", "Umberlee", "Utopia",
	"Vadera", "Vagra", "Vandor", "Ventax", "Xenon",
	"Xerxes", "Yew", "Yojimbo", "Zalkon", "Zuul",
}
